services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "apt update && apt install -y netcat-openbsd && nc -z postgres-test 5432 && nc -z redis-test 6379 && bun test"
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres-test:5432/telerpg
      - REDIS_URL=redis://redis-test:6379
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - postgres-test
      - redis-test

  postgres-test:
    image: postgres:17
    environment:
      - POSTGRES_DB=telerpg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d telerpg"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis-test:
    image: redis:8
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
