services:
  postgres-test:
    image: postgres:17
    environment:
      - POSTGRES_DB=telerpg_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d telerpg_test"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis-test:
    image: redis:8
    ports:
      - "6379:6379"
    volumes:
      - redis_test_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_test_data:
  redis_test_data: