networks:
  telerpg-test-network:
    driver: bridge

services:
  postgres_test:
    image: postgres:17
    networks:
      - telerpg-test-network
    environment:
      - POSTGRES_DB=telerpg_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis_test:
    image: redis:8
    networks:
      - telerpg-test-network
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  app_test:
    build:
      context: .
      dockerfile: Dockerfile.test
    networks:
      - telerpg-test-network
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgresql://postgres:password@postgres_test:5432/telerpg_test
      - REDIS_URL=redis://redis_test:6379
      - BOT_TOKEN=test_token
    depends_on:
      postgres_test:
        condition: service_healthy
      redis_test:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./scripts:/app/scripts